context('checking all links that open full list of names', () => {
    it('clicks, checks link content', () => {
      cy.visit('https://horo.mail.ru/namesecret')
      Cypress.on('uncaught:exception', (err, runnable) => {
          return false
        }) 
      cy.contains('[class="link__text"]','147').click()
      cy.request('https://horo.mail.ru/namesecret/a')
      .should((response) => {
        expect(response.status).to.eq(200)
      })
      cy.url().should('include', '/namesecret/a/')
      cy.go('back')
      cy.contains('[class="link__text"]','6').click()
      cy.request('https://horo.mail.ru/namesecret/b')
      .should((response) => {
        expect(response.status).to.eq(200)
      })
      cy.url().should('include', '/namesecret/b/')
      cy.go('back')
      cy.contains('[class="link__text"]','34').click()
      cy.request('https://horo.mail.ru/namesecret/v')
      .should((response) => {
        expect(response.status).to.eq(200)
      })
      cy.url().should('include', '/namesecret/v/')
      cy.go('back')
      cy.contains('[class="link__text"]','32').click()
      cy.request('https://horo.mail.ru/namesecret/g')
      .should((response) => {
        expect(response.status).to.eq(200)
      })
      cy.url().should('include', '/namesecret/g/')
      cy.go('back')
      cy.contains('[class="link__text"]','21').click({ force:true})
      cy.request('https://horo.mail.ru/namesecret/d')
      .should((response) => {
        expect(response.status).to.eq(200)
      })
      cy.url().should('include', '/namesecret/d/')
      cy.go('back')
      cy.contains('[class="link__text"]','24').click()
      cy.request('https://horo.mail.ru/namesecret/e')
      .should((response) => {
        expect(response.status).to.eq(200)
      })
      cy.url().should('include', '/namesecret/e/')
      cy.go('back')
      cy.contains('[class="link__text"]','Еще (3)').click({force: true})
      cy.request('https://horo.mail.ru/namesecret/z')
      .should((response) => {
        expect(response.status).to.eq(200)
      })
      cy.url().should('include', '/namesecret/z/')
      cy.go('back')
      cy.contains('[class="link__text"]','22').click()
      cy.request('https://horo.mail.ru/namesecret/i')
      .should((response) => {
        expect(response.status).to.eq(200)
      })
      cy.url().should('include', '/namesecret/i/')
      cy.go('back')
      cy.contains('[href="/namesecret/k/"]', '32').click()
      cy.request('https://horo.mail.ru/namesecret/k')
      .should((response) => {
        expect(response.status).to.eq(200)
      })
      cy.url().should('include', '/namesecret/k/')
      cy.go('back')
      cy.contains('[href="/namesecret/l/"]','Еще (21)').click({force: true})
      cy.request('https://horo.mail.ru/namesecret/l')
      .should((response) => {
        expect(response.status).to.eq(200)
      })
      cy.url().should('include', '/namesecret/l/')
      cy.go('back')
      cy.contains('[class="link__text"]','Еще (47)').click()
      cy.request('https://horo.mail.ru/namesecret/m')
      .should((response) => {
        expect(response.status).to.eq(200)
      })
      cy.url().should('include', '/namesecret/m/')
      cy.go('back')
      cy.contains('[class="link__text"]','13').click()
      cy.request('https://horo.mail.ru/namesecret/n')
      .should((response) => {
        expect(response.status).to.eq(200)
      })
      cy.url().should('include', '/namesecret/n/')
      cy.go('back')
      cy.contains('[class="link__text"]','Еще (7)').click({force: true})
      cy.request('https://horo.mail.ru/namesecret/o')
      .should((response) => {
        expect(response.status).to.eq(200)
      })
      cy.url().should('include', '/namesecret/o/')
      cy.go('back')
      cy.contains('[class="link__text"]','16').click()
      cy.request('https://horo.mail.ru/namesecret/p')
      .should((response) => {
        expect(response.status).to.eq(200)
      })
      cy.url().should('include', '/namesecret/p/')
      cy.go('back')
      cy.contains('[href="/namesecret/r/"]','21').click()
      cy.request('https://horo.mail.ru/namesecret/r')
      .should((response) => {
        expect(response.status).to.eq(200)
      })
      cy.url().should('include', '/namesecret/r/')
      cy.go('back')
      cy.contains('[class="link__text"]','33').click({force: true})
      cy.request('https://horo.mail.ru/namesecret/s')
      .should((response) => {
        expect(response.status).to.eq(200)
      })
      cy.url().should('include', '/namesecret/s/')
      cy.go('back')
      cy.contains('[class="link__text"]','8').click()
      cy.request('https://horo.mail.ru/namesecret/t')
      .should((response) => {
        expect(response.status).to.eq(200)
      })
      cy.url().should('include', '/namesecret/t/')
      cy.go('back')
      cy.contains('[class="link__text"]','Еще (1)').click({force: true})
      cy.request('https://horo.mail.ru/namesecret/u')
      .should((response) => {
        expect(response.status).to.eq(200)
      })
      cy.url().should('include', '/namesecret/u/')
      cy.go('back')
      cy.contains('[class="link__text"]','15').click({force: true})
      cy.request('https://horo.mail.ru/namesecret/f')
      .should((response) => {
        expect(response.status).to.eq(200)
      })
      cy.url().should('include', '/namesecret/f/')
      cy.go('back')
      cy.contains('[class="link__text"]','Еще (2)').click({force: true})
      cy.request('https://horo.mail.ru/namesecret/h')
      .should((response) => {
        expect(response.status).to.eq(200)
      })
      cy.url().should('include', '/namesecret/h/')
      cy.go('back')
      cy.contains('[class="link__text"]','Еще (14)').click({force: true})
      cy.request('https://horo.mail.ru/namesecret/je')
      .should((response) => {
        expect(response.status).to.eq(200)
      })
      cy.url().should('include', '/namesecret/je/')
    })
  })