context('checking all links', () => {
  it('clicks, checks link content', () => {
    cy.visit('https://horo.mail.ru/namesecret')
    Cypress.on('uncaught:exception', (err, runnable) => {
        return false
      }) 
    cy.contains('[class="filter__text"]','А').click()
    cy.request('https://horo.mail.ru/namesecret/a')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/a/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Б').click()
    cy.request('https://horo.mail.ru/namesecret/b')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/b/')
    cy.go('back')
    cy.contains('[href="/namesecret/v/"]','В').click()
    cy.request('https://horo.mail.ru/namesecret/v')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/v/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Г').click()
    cy.request('https://horo.mail.ru/namesecret/g')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/g/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Д').click()
    cy.request('https://horo.mail.ru/namesecret/d')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/d/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Е').click()
    cy.request('https://horo.mail.ru/namesecret/e')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/e/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Ж').click()
    cy.request('https://horo.mail.ru/namesecret/zh')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/zh/')
    cy.go('back')
    cy.contains('[class="filter__text"]','З').click()
    cy.request('https://horo.mail.ru/namesecret/z')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/z/')
    cy.go('back')
    cy.contains('[class="filter__text"]','И').click()
    cy.request('https://horo.mail.ru/namesecret/i')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/i/')
    cy.go('back')
    cy.contains('[class="filter__text"]','К').click()
    cy.request('https://horo.mail.ru/namesecret/k')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/k/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Л').click()
    cy.request('https://horo.mail.ru/namesecret/l')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/l/')
    cy.go('back')
    cy.contains('[class="filter__text"]','М').click()
    cy.request('https://horo.mail.ru/namesecret/m')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/m/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Н').click()
    cy.request('https://horo.mail.ru/namesecret/n')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/n/')
    cy.go('back')
    cy.contains('[class="filter__text"]','О').click()
    cy.request('https://horo.mail.ru/namesecret/o')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/o/')
    cy.go('back')
    cy.contains('[class="filter__text"]','П').click()
    cy.request('https://horo.mail.ru/namesecret/p')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/p/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Р').click()
    cy.request('https://horo.mail.ru/namesecret/r')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/r/')
    cy.go('back')
    cy.contains('[class="filter__text"]','С').click()
    cy.request('https://horo.mail.ru/namesecret/s')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/s/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Т').click()
    cy.request('https://horo.mail.ru/namesecret/t')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/t/')
    cy.go('back')
    cy.contains('[class="filter__text"]','У').click()
    cy.request('https://horo.mail.ru/namesecret/u')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/u/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Ф').click()
    cy.request('https://horo.mail.ru/namesecret/f')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/f/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Х').click()
    cy.request('https://horo.mail.ru/namesecret/h')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/h/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Ц').click()
    cy.request('https://horo.mail.ru/namesecret/ts')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/ts/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Э').click()
    cy.request('https://horo.mail.ru/namesecret/je')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/je/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Ю').click()
    cy.request('https://horo.mail.ru/namesecret/ju')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/ju/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Я').click()
    cy.request('https://horo.mail.ru/namesecret/ja')
    .should((response) => {
      expect(response.status).to.eq(200)
    })
    cy.url().should('include', '/namesecret/ja/')
  })
})