context('checking all links that open full list of male names', () => {
    it('clicks, checks link content', () => {
      cy.visit('https://horo.mail.ru/namesecret/male')
      Cypress.on('uncaught:exception', (err, runnable) => {
          return false
        }) 
      cy.contains('[class="filter__text"]','А').click()
      cy.request('https://horo.mail.ru/namesecret/male/a')
      .should((response) => {
        expect(response.status).to.not.eq(404)
      })
      cy.url().should('include', '/namesecret/male/a/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Б').click()
      cy.request('https://horo.mail.ru/namesecret/male/b')
      .should((response) => {
        expect(response.status).to.not.eq(404)
      })
      cy.url().should('include', '/namesecret/male/b/')
      cy.go('back')
      cy.contains('[href="/namesecret/male/v/"]','В').click()
      cy.request('https://horo.mail.ru/namesecret/male/v')
      .should((response) => {
        expect(response.status).to.not.eq(404)
      })
      cy.url().should('include', '/namesecret/male/v/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Г').click()
      cy.request('https://horo.mail.ru/namesecret/male/g')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/male/g/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Д').click()
      cy.request('https://horo.mail.ru/namesecret/male/d')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/male/d/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Е').click()
      cy.request('https://horo.mail.ru/namesecret/male/e')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/male/e/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Ж').click()
      cy.request('https://horo.mail.ru/namesecret/male/je')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/male/zh/')
      cy.go('back')
      cy.contains('[class="filter__text"]','З').click()
      cy.request('https://horo.mail.ru/namesecret/male/z')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/male/z/')
      cy.go('back')
      cy.contains('[class="filter__text"]','И').click()
      cy.request('https://horo.mail.ru/namesecret/male/i')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/male/i/')
      cy.go('back')
      cy.contains('[class="filter__text"]','К').click()
      cy.request('https://horo.mail.ru/namesecret/male/k')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/male/k/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Л').click()
      cy.request('https://horo.mail.ru/namesecret/male/l')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/male/l/')
      cy.go('back')
      cy.contains('[class="filter__text"]','М').click()
      cy.request('https://horo.mail.ru/namesecret/male/m')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/male/m/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Н').click()
      cy.request('https://horo.mail.ru/namesecret/male/n')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/male/n/')
      cy.go('back')
      cy.contains('[class="filter__text"]','О').click()
      cy.request('https://horo.mail.ru/namesecret/male/o')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/male/o/')
      cy.go('back')
      cy.contains('[class="filter__text"]','П').click()
      cy.request('https://horo.mail.ru/namesecret/male/p')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/male/p/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Р').click()
      cy.request('https://horo.mail.ru/namesecret/male/r')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/male/r/')
      cy.go('back')
      cy.contains('[class="filter__text"]','С').click()
      cy.request('https://horo.mail.ru/namesecret/male/s')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/male/s/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Т').click()
      cy.request('https://horo.mail.ru/namesecret/male/t')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/male/t/')
      cy.go('back')
      cy.contains('[class="filter__text"]','У').click()
      cy.request('https://horo.mail.ru/namesecret/male/u')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/male/u/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Ф').click()
      cy.request('https://horo.mail.ru/namesecret/male/f')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/male/f/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Х').click()
      cy.request('https://horo.mail.ru/namesecret/male/h')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/male/h/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Ц').click()
      cy.request('https://horo.mail.ru/namesecret/male/ts')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/male/ts/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Э').click()
      cy.request('https://horo.mail.ru/namesecret/male/je')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/male/je/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Ю').click()
      cy.request('https://horo.mail.ru/namesecret/male/ju')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/male/ju/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Я').click()
      cy.request('https://horo.mail.ru/namesecret/male/ja')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/male/ja/')
    })
})