context('checking all links that open full list of female names', () => {
    it('clicks, checks link content', () => {
      cy.visit('https://horo.mail.ru/namesecret/female')
      Cypress.on('uncaught:exception', (err, runnable) => {
          return false
        }) 
      cy.contains('[class="filter__text"]','А').click()
      cy.request('https://horo.mail.ru/namesecret/female/a')
      .should((response) => {
        expect(response.status).to.not.eq(404)
      })
      cy.url().should('include', '/namesecret/female/a/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Б').click()
      cy.request('https://horo.mail.ru/namesecret/female/b')
      .should((response) => {
        expect(response.status).to.not.eq(404)
      })
      cy.url().should('include', '/namesecret/female/b/')
      cy.go('back')
      cy.contains('[href="/namesecret/male/v/"]','В').click()
      cy.request('https://horo.mail.ru/namesecret/female/v')
      .should((response) => {
        expect(response.status).to.not.eq(404)
      })
      cy.url().should('include', '/namesecret/female/v/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Г').click()
      cy.request('https://horo.mail.ru/namesecret/female/g')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/female/g/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Д').click()
      cy.request('https://horo.mail.ru/namesecret/female/d')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/female/d/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Е').click()
      cy.request('https://horo.mail.ru/namesecret/female/e')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/female/e/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Ж').click()
      cy.request('https://horo.mail.ru/namesecret/female/je')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/female/zh/')
      cy.go('back')
      cy.contains('[class="filter__text"]','З').click()
      cy.request('https://horo.mail.ru/namesecret/female/z')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/female/z/')
      cy.go('back')
      cy.contains('[class="filter__text"]','И').click()
      cy.request('https://horo.mail.ru/namesecret/female/i')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/female/i/')
      cy.go('back')
      cy.contains('[class="filter__text"]','К').click()
      cy.request('https://horo.mail.ru/namesecret/female/k')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/female/k/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Л').click()
      cy.request('https://horo.mail.ru/namesecret/female/l')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/female/l/')
      cy.go('back')
      cy.contains('[class="filter__text"]','М').click()
      cy.request('https://horo.mail.ru/namesecret/female/m')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/female/m/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Н').click()
      cy.request('https://horo.mail.ru/namesecret/female/n')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/female/n/')
      cy.go('back')
      cy.contains('[class="filter__text"]','О').click()
      cy.request('https://horo.mail.ru/namesecret/female/o')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/female/o/')
      cy.go('back')
      cy.contains('[class="filter__text"]','П').click()
      cy.request('https://horo.mail.ru/namesecret/female/p')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/female/p/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Р').click()
      cy.request('https://horo.mail.ru/namesecret/female/r')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/female/r/')
      cy.go('back')
      cy.contains('[class="filter__text"]','С').click()
      cy.request('https://horo.mail.ru/namesecret/female/s')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/female/s/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Т').click()
      cy.request('https://horo.mail.ru/namesecret/female/t')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/female/t/')
      cy.go('back')
      cy.contains('[class="filter__text"]','У').click()
      cy.request('https://horo.mail.ru/namesecret/female/u')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/female/u/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Ф').click()
      cy.request('https://horo.mail.ru/namesecret/female/f')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/female/f/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Х').click()
      cy.request('https://horo.mail.ru/namesecret/female/h')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/female/h/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Ц').click()
      cy.request('https://horo.mail.ru/namesecret/female/ts')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/female/ts/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Э').click()
      cy.request('https://horo.mail.ru/namesecret/female/je')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/female/je/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Ю').click()
      cy.request('https://horo.mail.ru/namesecret/female/ju')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/female/ju/')
      cy.go('back')
      cy.contains('[class="filter__text"]','Я').click()
      cy.request('https://horo.mail.ru/namesecret/female/ja')
      .should((response) => {
        expect(response.status).to.not.eq(400)
      })
      cy.url().should('include', '/namesecret/female/ja/')
    })
})