context('checking all links', () => {
  it('clicks, checks link content', () => {
    cy.visit('https://horo.mail.ru/namesecret')
    Cypress.on('uncaught:exception', (err, runnable) => {
        return false
      }) 
    cy.contains('[class="filter__text"]','А').click()
    cy.url().should('include', '/namesecret/a/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Б').click()
    cy.url().should('include', '/namesecret/b/')
    cy.go('back')
    cy.contains('[href="/namesecret/v/"]','В').click()
    cy.url().should('include', '/namesecret/v/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Г').click()
    cy.url().should('include', '/namesecret/g/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Д').click()
    cy.url().should('include', '/namesecret/d/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Е').click()
    cy.url().should('include', '/namesecret/e/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Ж').click()
    cy.url().should('include', '/namesecret/zh/')
    cy.go('back')
    cy.contains('[class="filter__text"]','З').click()
    cy.url().should('include', '/namesecret/z/')
    cy.go('back')
    cy.contains('[class="filter__text"]','И').click()
    cy.url().should('include', '/namesecret/i/')
    cy.go('back')
    cy.contains('[class="filter__text"]','К').click()
    cy.url().should('include', '/namesecret/k/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Л').click()
    cy.url().should('include', '/namesecret/l/')
    cy.go('back')
    cy.contains('[class="filter__text"]','М').click()
    cy.url().should('include', '/namesecret/m/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Н').click()
    cy.url().should('include', '/namesecret/n/')
    cy.go('back')
    cy.contains('[class="filter__text"]','О').click()
    cy.url().should('include', '/namesecret/o/')
    cy.go('back')
    cy.contains('[class="filter__text"]','П').click()
    cy.url().should('include', '/namesecret/p/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Р').click()
    cy.url().should('include', '/namesecret/r/')
    cy.go('back')
    cy.contains('[class="filter__text"]','С').click()
    cy.url().should('include', '/namesecret/s/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Т').click()
    cy.url().should('include', '/namesecret/t/')
    cy.go('back')
    cy.contains('[class="filter__text"]','У').click()
    cy.url().should('include', '/namesecret/u/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Ф').click()
    cy.url().should('include', '/namesecret/f/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Х').click()
    cy.url().should('include', '/namesecret/h/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Ц').click()
    cy.url().should('include', '/namesecret/ts/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Э').click()
    cy.url().should('include', '/namesecret/je/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Ю').click()
    cy.url().should('include', '/namesecret/ju/')
    cy.go('back')
    cy.contains('[class="filter__text"]','Я').click()
    cy.url().should('include', '/namesecret/ja/')
  })
})